### ISSUE TITLE
Pic2cam apk

### ISSUE THREAD

**Issue by Ridasa** [adriangl/pict2cam#101]
Hello! I am using redme 9c.pic2cam apk not working in my cellphone.please resolve my issue.

**Comment by adriangl** [comment]
Hello @Ridasa!

Please fill the following details so I can help you:
 - App Version
 - Android device
 - Android version
 - What's the bug about

Thanks!

**Comment by Ridasa** [comment]
- App Version  1.3.1
   - Android device  Redme 9C
   - Android version  10 QP1A.190711.020

Fake camera app not worked in my cell phone when i have updated my system.
Please reslove my issue i shall be very thankful to you.
