### ISSUE TITLE
Send picture to Whatsapp Camera

### ISSUE THREAD

**Issue by duduccosta** [adriangl/pict2cam#140]
Hi.

I want to automate the whatsapp qrcode scanner (Adding Devices).
So what I need is send to whatsapp camera the content of qrcode (which i already have).
I have both (image and string content).

Is it possible using pict2cam?
Thanks.

**Comment by adriangl** [comment]
Hello @duduccosta!

Unfortunately not, Pict2Cam can't hook into camera inputs. 
WhatsApp doesn't use the Android Intent system for taking pictures (which Pict2Cam can hook into) or video: they bundle their own camera implementation that doesn't rely on Intents, but uses the device's camera input directly without third party apps.
You would need a way to replace the device's camera input with your own images or video in order for that to work, most likely needing to root your device (so you can manipulate the I/O of the OS).

I'm sorry that I can't provide you with much more information about this, I've tried to find a way to do this from some time to no avail, so if you ever find something, please let me know :)

Regards
