### ISSUE TITLE
Not working on some app - App those use custom camera

### ISSUE THREAD

**Issue by Riyaz7364** [adriangl/pict2cam#141]
**Summary and context of the enhancement**
I was using a barcode scanner app(It's my company app) In the old version of my company app was working with pict2cam perfectly but now they use a custom camera maybe using CameraX. Now when click on the camera button camera will open without any popup. Can you fix it or maybe provide a solution?

I'm using android 8.1
I also tried with an android emulator with android 7.0+7.1

**Comment by adriangl** [comment]
Hello!
Unfortunately Pict2Cam can only hook into apps that take pictures with an external application, as mentioned in the help section of the app. 
If the app that you're using now bundles their own camera implementation, Pict2Cam won't work any longer with it, I'm afraid.

Sorry and regards.
