### ISSUE TITLE
HELP!!

### ISSUE THREAD

**Issue by tanu771** [adriangl/pict2cam#177]
I need a virtual camera to override the system camera on android 11+ phone to stream frames that are sourced from an image file. Basically injecting image into the camera device.

I have **both root access and unlocked bootloader** on my phone.

Any Ideas?

**Comment by adriangl** [comment]
Hello!
Unfortunately Pict2Cam cannot do that, sorry. The app hooks the system intents for external camera app usage, but it cannot override a camera stream.

Maybe you can do something with that root access, but I cannot say for sure.

Sorry that I can't be of more help.
