### ISSUE TITLE
Front Camera

### ISSUE THREAD

**Issue by NotDhe2** [adriangl/pict2cam#28]
**Summary and context of the enhancement**
Exact same features but for front camera(selfie/the one literally on the top of the screen. NOT THE BACK camera.). Notice it work for main camera but  when I tried to use main camera I didn't get the option to choose from using pict2cam / camera. Why? Open more availability for using this app. So far didn't see an app can do front camera... 

**Suggested implementation**
Not programmer. I guess exact same thing but open another method when front camera being called, add pict2cam into it?? sorry not really teach person.

**Additional documentation**
I have none I dont know. U mean the demand of this feature? google reddit front fake camera/xda/forums probably have tons.

**Comment by adriangl** [comment]
Hi @NotDhe2!

Hmmm, I'm not sure if that's possible. Do you know of apps that request taking pictures with the front camera with the system's camera? Just so I can do some research on them :)

**Comment by NotDhe2** [comment]
How do I talk to you privately
